import random


def main() -> dict:
    prompt_dict = {
        "guitar": "In a vintage music shop filled with aged instruments and faded posters, a classic acoustic guitar hangs on a wall display. The shop has wooden floors with visible scuff marks and shelves lined with sheet music and old amplifiers. Soft, warm - toned lighting illuminates the space, casting a nostalgic glow. The guitar's wooden body is covered in a random yet evenly - spaced assortment of cool, music - themed stickers. There are stickers of iconic music notes in iridescent colors, band logos in bold, edgy fonts that seem to pop off the surface, and small musical instruments like miniature trumpets and drums. Each sticker has been carefully placed across the entire surface, from the headstock down to the body, creating a unique and eye - catching design. A gentle beam of light from a spotlight above shines directly on the guitar, making the uniformly - distributed stickers stand out vividly against the backdrop of the music shop's rustic charm.",
        "phone": "A hand with black and blue gradient nail polish holds two white smartphones. The custom-made phone cases are covered with various bright and eye-catching stickers, ranging from trendy icons to miniature artworks. The background is a light gray wall illuminated by soft lighting, and there is a white book with black text next to it.",
        "suitcase": "A young woman with fair skin and straight brown hair is wearing a white long-sleeved shirt, black pants, and a navy blue baseball cap. She is squatting next to a vintage gray suitcase, which is covered with various stickers from different travel experiences. The background is a sunlit urban park with lush greenery, tall trees, and a multi-story building with a red sign in the distance.",
        "laptop": "A white lightweight laptop is placed on the table, and its entire back cover is regularly covered with various stickers. The stickers include cute animals, motivational quotes in colorful letters, and decorative patterns such as stars and hearts. In the classroom where it is located, there are rows of desks and chairs, and the blackboard in front is filled with mathematical formulas. The sunlight shines on the laptop through the window.",
        "skateboarder": "A vividly - hued skateboard commands attention, its deck and trucks entirely blanketed in an eye - catching medley of bright street - style stickers. Prominent among them are graffiti - style designs with bold, swirling lines and vivid splashes of color that seem to tell urban stories. Skate brand logos, both well - known and niche, are emblazoned with pride, their distinct symbols adding an air of authenticity. Cool geometric patterns, from sharp triangles to interlocking hexagons, create a dynamic visual rhythm. The skateboard's surface is a canvas where creativity and street culture collide, with each sticker carefully placed to maximize impact. In the background, the faint outlines of an urban skate park with colorful ramps and street - art - covered walls suggest the lively context, but the skateboard and its stickers remain the indisputable focal point, their details accentuated by the strong sunlight that glistens off the sticker surfaces, making them pop with energy.",
        "helmet": "A motocross helmet takes center stage, its surface completely covered with an array of tough motocross - themed stickers. There are skulls donning racing goggles with detailed features, speed - related symbols like dynamic lightning bolts and revved - up speedometer needles, and logos of popular motocross brands, all arranged to make the stickers stand out prominently.",
        "cup": "A cozy rural café is filled with sunlight filtering through gingham - patterned curtains, casting a warm glow on the vintage wooden tables. On one of the tables lies a rustic ceramic mug. The original off - white surface of the mug is completely covered with an evenly - distributed array of stickers. These stickers feature a diverse range of elements. There are colorful, smiling fairy figures with shimmering wings straight out of a fairy - tale. There are also vintage - style travel labels printed with names of famous cities around the world like Paris, Rome along with delicate landmark patterns. Additionally, there are simple yet cute hand - drawn fruits such as strawberries and lemons, each with carefully depicted details. The café walls are adorned with oil paintings of rural landscapes, and wicker chairs are placed around. The rich aroma of coffee fills the air, making the evenly - distributed stickers on the mug stand out prominently in this warm and inviting atmosphere."
    }

    return {
        "result": random.sample(prompt_dict.values(), 5),
    }
